### ISSUE TITLE
Failed to retrieve user 

### ISSUE THREAD

**Issue by AlMaVizca** [zzamboni/750words-client#1]
Hey! Thanks for this helper to promote writing.

I've failed to login following the readme steps, and looking at the code, and doing some debug.
I've found that the user is not loading from the auth-source. The error seems to be at the next line.
https://github.com/zzamboni/750words-client/blob/0fed7621c04debad64ea6455455494d4e6eb03fa/750words.el#L71

Since create is optional and becomes nil, from the optional parameter `save` at
https://github.com/zzamboni/750words-client/blob/0fed7621c04debad64ea6455455494d4e6eb03fa/750words.el#L81

This leaves an empty value at USER_750WORDS env.

Not sure how it should be fixed though :sweat_smile:

**Comment by zzamboni** [comment]
Hi @AlMaVizca - glad you've found this useful.

Maybe this is not too clear from the documentation, but the default behavior assumes the credentials are already stored in your chosen auth-source. If you are using `~/.authinfo.gpg` or some other source that supports creation (not all of them do - e.g. Apple Keychain), you can initialize it by running `750words-credentials-setenv` with `create` set to `t`. Interactively, you can do this by prefixing the command with `C-u`. This is mentioned in the README:

> If the auth-source you use supports entry creation (for example, `~/.authinfo.gpg` does) you can run `C-u M-x 750words-credentials-setenv` - you will be prompted for your credentials and they will be automatically stored.

Afterwards, the credentials should be found correctly.

Does this help, or am I misunderstanding your question?

**Comment by AlMaVizca** [comment]
yes, that helps, I didn't notice that the save parameter was the same as create. Thanks a lot @zzamboni!
I'm using [password-store](https://www.passwordstore.org/), it's common to use the login field to set the user there,
In case anybody else uses the same, the field has to be called `user`. That  plus the save parameter as t solved my issue of having the `USER_750WORDS` empty.
